# Generated by Django 4.2.2 on 2023-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creat_time',
            field=models.DateField(null=True),
        ),
    ]
