# Generated by Django 4.2.2 on 2023-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_employee_creat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('price', models.IntegerField()),
                ('level', models.SmallIntegerField(choices=[(3, 'Low'), (1, 'Top'), (2, 'Middle')], default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'Occupied'), (2, 'Free')], default=2)),
            ],
        ),
    ]
