# Generated by Django 4.2.2 on 2023-07-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='level',
            field=models.SmallIntegerField(choices=[(1, 'Top'), (2, 'Middle'), (3, 'Low')], default=1),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'Free'), (1, 'Occupied')], default=2),
        ),
    ]
