# Generated by Django 4.2.2 on 2023-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default='asdf', max_length=32),
            preserve_default=False,
        ),
    ]
