# Generated by Django 4.2.2 on 2023-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_logo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='city/'),
        ),
    ]
