# Generated by Django 4.2.2 on 2023-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_admin_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='logo',
            field=models.ImageField(default='/media/user/default_logo.jpg', upload_to='user/'),
        ),
    ]
