# Generated by Django 4.2.2 on 2023-07-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_admin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='bilibili@163.com', max_length=254),
            preserve_default=False,
        ),
    ]
